### PR TITLE
fix: for custom url, consider any protocol

### PR DESCRIPTION
**Pull request by amithm7**
fixes gh-310

### CODE REVIEW

**Comment by cadeyrn** [comment]
Thanks for your PR! I solved it a bit different because we can't allow arbitrary protocols. So we need to be explicit about the protocol and only allow https://, http:// and moz-extension://.

**Comment by amithm7** [comment]
@cadeyrn Thanks for fixing the issue.

Two things:

1) There is contradictory statement in the README file.

> Automatically adds “http://” if _protocol_ is missing from a URL

Emphasis mine. You might want to fix that.

2) > because we can't allow arbitrary protocols

What is the reason for this? Does any protocol interfere with this extension?

Any security issue, what protocols are supported is already handled by firefox.

**Comment by cadeyrn** [comment]
> Emphasis mine. You might want to fix that.

I will do that, thanks. There will be a general check of the README file before the next update.

> What is the reason for this? Does any protocol interfere with this extension?

You can't use file://, for example. And it's always better to be explicit about what is allowed and not to hope that every user input works.

> Any security issue, what protocols are supported is already handled by firefox.

The extension should never allow something that is not supported by Firefox.

**Comment by amithm7** [comment]
> it's always better to be explicit about what is allowed and not to hope that every user input works.

In that case, a feedback / error message if unsupported (by firefox) `protocol://` is detected would make a for a better user experience, than just prepending https. A new issue can be created for this, for if somebody decides to work on it.

> You can't use file://, for example.
> The extension should never allow something that is not supported by Firefox.

I just don't understand the reasoning for it, that's what I was asking. But okay, firefox, doesn't support many protocols anyway.

**Comment by cadeyrn** [comment]
> In that case, a feedback / error message if unsupported (by firefox) protocol:// is detected would make a for a better user experience, than just prepending https. A new issue can be created for this, for if somebody decides to work on it.

Yes, please. This is an enhancement request on its own.

> I just don't understand the reasoning for it, that's what I was asking. But okay, firefox, doesn't support many protocols anyway.

Extensions can't access local files for security reasons.

**Pull request closed without merging**
