### PR TITLE
fix about:blank option fail when custom url is configured

### PR DESCRIPTION
**Pull request by tiansh**
Bug reproduce:

1. Chose Custom URL
2. Enter some valid URL (e.g. https://www.example.com/ )
3. Chose blank page (about:blank)
4. Open a new tab

Expect: Open about:blank
Actual: Open example.com

### CODE REVIEW

**Comment by tiansh** [comment]
Aha, maybe wrong branch?

**Comment by cadeyrn** [comment]
Thank you for the PR! The master branch is the correct branch. Why did you close the PR?

**Comment by tiansh** [comment]
I just cannot reproduce this problem on a release version. And, I just wonder maybe I'm working on a wrong branch.

**Comment by cadeyrn** [comment]
Thank you for your PR, I had to fix it in a different way.

**Pull request closed without merging**
