### PR TITLE
Add Chinese (S) translation back

### PR DESCRIPTION
**Pull request by tiansh**
Add Chinese (S) translation back

some text is moved from html / manifest to locales to fit the requirement of translation

### CODE REVIEW

**Comment by tiansh** [comment]
Is master the correct branch for translation?

**Comment by cadeyrn** [comment]
Thank you for the PR. The master branch is the correct branch.

Are all the changes to the other locales and the HTML files really necessary? It's very error prone to depend on spaces at the end of translations or on colon at the beginning of the string.

**Comment by tiansh** [comment]
First, Chinese use full width punctuation (`；：，。` instead of `;:,.`) to meet its width of text. Using English one is just a little ugly (and also incorrect). (zh-TW, ja, and other east Asia language share similar punctuation, but not exactly same)

Second is about white space. It's common to add a space between any han-characters and Latin letters for better appearance. Missing such a space only looks ugly, but at least also correct.

Another problem here is the order of words: "provided by xyz" should be translated to “由 xyz 提供”. Although it could be reordered to some strange order to fit the limitation. But that's not what people saying normally.

Currently these changing is focused on minimal changing on HTML and other JS files. We could support translation strings like "provided by $1". But it maybe need more changes on JS codes. If you'd like chose this option, I will update this PR later.

**Comment by tiansh** [comment]
Hey, What about this way? No spaces at the end / beginning any more but a `{0}` placeholder.

**Comment by cadeyrn** [comment]
Thank you very much, that's a much better approach! I'll test your PR later and will merge it once tested!

**Comment by cadeyrn** [comment]
Works great, thank you again!

**Pull request merged**
